### ISSUE TITLE
Undefined index: rating 

### ISSUE THREAD

**Issue by nikola-n** [mvdnbrk/kiyoh-php-api#14]
https://github.com/mvdnbrk/kiyoh-php-api/blob/833f38e30c76c3cba0bec358ada3fa43f687040a/src/Feed.php#L155

Hi, nice package! Just a small issue I encountered, when using the withMigrated, some of the reviews may not contain the rating index.

Maybe just add:
```
 return [ 
             $key => $item['rating']  ?? null
          ];
```
or

```
 return [
              $key => Arr::get($item, 'rating'),
          ];
```

**Comment by mvdnbrk** [comment]
Hm a review without a rating? That’s odd.

Rating is an unsigned tiny integer in the review model, so that should be 0 instead of null.

Can you make a PR? Thanks.
