### ISSUE TITLE
Version request without laravel implementation.

### ISSUE THREAD

**Issue by mikevandiepen** [mvdnbrk/kiyoh-php-api#4]
I want to use your library to build a custom Magento-1 module upon. The issue is, since magento is such a vast project I want to keep the codebase at minimum.

Therefore it would be nice if there was a barebone branch of the project, for example a branch of the project without the laravel code in it.

**Comment by mvdnbrk** [comment]
To support Laravel there is only a `ServiceProvider` class and some config and db files. These won't affect the library so there is no big thing here.

Sure, it would be nice to have these completely separated but don't have the time to work on this package.
